#!/bin/sh
# PocketBase on PostgreSQL - installer.
#
# Downloads nothing else: it writes a compose file and a .env, starts the stack
# and creates the first superuser.
#
#   curl -fsSL https://raw.githubusercontent.com/mwakalinga/pocketbase-postgres/master/install.sh -o install.sh
#   sh install.sh
#
# Read it before running it - that is why it is a download rather than a pipe
# into a shell.
#
# Non-interactive (for scripts and CI):
#
#   sh install.sh --yes --port 8090 --dir ./pocketbase
#
# Options:
#   --dir PATH        where to install            (default ./pocketbase)
#   --port N          host port for the dashboard (default 8090)
#   --db-user NAME    database user               (default pocketbase)
#   --db-name NAME    database name               (default pocketbase)
#   --db-pass SECRET  database password           (default: generated)
#   --tag TAG         image tag to deploy         (default latest)
#   --admin-email X   first superuser email       (default: asked, or skipped)
#   --admin-pass X    first superuser password
#   --yes             accept defaults, never prompt
set -eu

REPO_IMAGE="${PB_IMAGE_REPO:-ghcr.io/mwakalinga/pocketbase-postgres}"

INSTALL_DIR="./pocketbase"
PB_PORT="8090"
DB_USER="pocketbase"
DB_NAME="pocketbase"
DB_PASS=""
IMAGE_TAG="latest"
ADMIN_EMAIL=""
ADMIN_PASS=""
ASSUME_YES="0"

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --dir) INSTALL_DIR="${2:-}"; shift 2 ;;
        --port) PB_PORT="${2:-}"; shift 2 ;;
        --db-user) DB_USER="${2:-}"; shift 2 ;;
        --db-name) DB_NAME="${2:-}"; shift 2 ;;
        --db-pass) DB_PASS="${2:-}"; shift 2 ;;
        --tag) IMAGE_TAG="${2:-}"; shift 2 ;;
        --admin-email) ADMIN_EMAIL="${2:-}"; shift 2 ;;
        --admin-pass) ADMIN_PASS="${2:-}"; shift 2 ;;
        --yes|-y) ASSUME_YES="1"; shift ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        *) die "unknown option: $1 (try --help)" ;;
    esac
done

# ---------------------------------------------------------------- checks ----
command -v docker >/dev/null 2>&1 || die "docker is not installed - see https://docs.docker.com/get-docker/"

if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
else
    die "docker compose is not available - install the Compose plugin"
fi

docker info >/dev/null 2>&1 || die "cannot talk to the docker daemon - is it running, and is your user in the 'docker' group?"

# --------------------------------------------------------------- prompts ----
# read from the terminal, so prompting still works if this script was piped
ask() { # ask VAR_NAME "prompt" "default"
    _def="$3"
    if [ "$ASSUME_YES" = "1" ] || [ ! -t 0 ] && [ ! -r /dev/tty ]; then
        eval "$1=\"\$_def\""
        return
    fi
    printf '%s [%s]: ' "$2" "$_def" > /dev/tty
    read -r _ans < /dev/tty || _ans=""
    [ -n "$_ans" ] || _ans="$_def"
    eval "$1=\"\$_ans\""
}

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 24 | tr -d '/+=' | cut -c1-24
    else
        # no openssl: fall back to the kernel's entropy
        tr -dc 'A-Za-z0-9' < /dev/urandom 2>/dev/null | head -c 24
    fi
}

echo "PocketBase on PostgreSQL - installer"
echo

if [ "$ASSUME_YES" != "1" ]; then
    ask INSTALL_DIR "Install directory" "$INSTALL_DIR"
    ask PB_PORT     "Port for the dashboard and API" "$PB_PORT"
    ask DB_USER     "Database user" "$DB_USER"
    ask DB_NAME     "Database name" "$DB_NAME"
    ask IMAGE_TAG   "Image tag" "$IMAGE_TAG"
fi

[ -n "$DB_PASS" ] || DB_PASS="$(generate_secret)"
[ -n "$DB_PASS" ] || die "could not generate a database password - pass --db-pass"

case "$PB_PORT" in
    ''|*[!0-9]*) die "port must be a number, got '$PB_PORT'" ;;
esac

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

if [ -f compose.yaml ] || [ -f .env ]; then
    ask _overwrite "An install already exists here. Overwrite compose.yaml and .env? (y/N)" "N"
    case "$_overwrite" in
        y|Y|yes|YES) : ;;
        *) die "left the existing install untouched" ;;
    esac
fi

# ------------------------------------------------------------- write files --
cat > compose.yaml <<'COMPOSE_EOF'
# PocketBase on PostgreSQL. Generated by install.sh.
#
#   docker compose up -d          start
#   docker compose logs -f        follow the logs
#   docker compose down           stop (keeps your data)
#   docker compose down -v        stop and DELETE all data
#
# Settings live in .env next to this file.

name: pocketbase

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    volumes:
      # postgres:18+ expects a single mount here and puts the cluster in a
      # major-version subdirectory beneath it
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    # not published to the host - only the app reaches it, over this network

  pocketbase:
    image: ${PB_IMAGE:?}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PB_DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      # optional; when set it must be exactly 32 characters
      PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY:-}
    ports:
      - "${PB_PORT}:8090"
    volumes:
      # uploaded files and generated backups. Your records live in Postgres,
      # so this volume alone is NOT a complete backup.
      - pbdata:/pb_data

volumes:
  pgdata:
  pbdata:
COMPOSE_EOF

umask 077
cat > .env <<ENV_EOF
# Generated by install.sh. Keep this file private - it holds your database
# password.

POSTGRES_USER=$DB_USER
POSTGRES_DB=$DB_NAME
POSTGRES_PASSWORD=$DB_PASS

PB_IMAGE=$REPO_IMAGE:$IMAGE_TAG
PB_PORT=$PB_PORT

# Optional. Exactly 32 characters. Encrypts stored SMTP/S3 credentials at rest;
# losing it makes those settings unreadable. Generate one with:
#   openssl rand -base64 24 | cut -c1-32
PB_ENCRYPTION_KEY=
ENV_EOF
umask 022

echo
echo "wrote $(pwd)/compose.yaml"
echo "wrote $(pwd)/.env"
echo

# ------------------------------------------------------------------ start ---
echo "starting..."
$COMPOSE up -d

printf 'waiting for the server'
i=0
while [ "$i" -lt 60 ]; do
    if curl -fsS -m 3 "http://127.0.0.1:$PB_PORT/api/health" >/dev/null 2>&1; then
        echo " ok"
        break
    fi
    printf '.'
    i=$((i + 1))
    sleep 2
done

if ! curl -fsS -m 3 "http://127.0.0.1:$PB_PORT/api/health" >/dev/null 2>&1; then
    echo
    echo "the server did not become healthy in time. Check the logs with:"
    echo "  cd $(pwd) && $COMPOSE logs"
    exit 1
fi

# ------------------------------------------------------------ superuser -----
if [ -z "$ADMIN_EMAIL" ] && [ "$ASSUME_YES" != "1" ]; then
    ask ADMIN_EMAIL "First superuser email (blank to skip)" ""
fi

if [ -n "$ADMIN_EMAIL" ]; then
    if [ -z "$ADMIN_PASS" ]; then
        ask ADMIN_PASS "First superuser password (min 10 characters)" ""
    fi
    if [ -n "$ADMIN_PASS" ]; then
        $COMPOSE exec -T pocketbase pb superuser upsert "$ADMIN_EMAIL" "$ADMIN_PASS" \
            || echo "could not create the superuser - do it later with: $COMPOSE exec pocketbase pb superuser upsert EMAIL PASSWORD"
    fi
fi

echo
echo "----------------------------------------------------------------"
echo " PocketBase is running"
echo
echo "   dashboard : http://localhost:$PB_PORT/_/"
echo "   directory : $(pwd)"
echo
echo "   logs      : cd $(pwd) && $COMPOSE logs -f"
echo "   stop      : cd $(pwd) && $COMPOSE down"
echo "   superuser : cd $(pwd) && $COMPOSE exec pocketbase pb superuser upsert EMAIL PASSWORD"
echo
echo " Your database password is in .env - back that file up."
echo "----------------------------------------------------------------"
